use_field_init_shorthand = true
newline_style = "Unix"
array_width = 80
wrap_comments = true
comment_width = 120
condense_wildcard_suffixes = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = true
type_punctuation_density = "Wide"
use_small_heuristics = "Max"